// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlWYsHR6k6coZxijduaoxeXUPf-2hWAko',
    appId: '1:664168983442:web:338cfec46a2aaee8ccef4b',
    messagingSenderId: '664168983442',
    projectId: 'crypto-wallet-app-2fb95',
    authDomain: 'crypto-wallet-app-2fb95.firebaseapp.com',
    storageBucket: 'crypto-wallet-app-2fb95.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9jYZjflqTTPjPLEkSON802inSWwrYV8Y',
    appId: '1:664168983442:android:280435cfee9dff80ccef4b',
    messagingSenderId: '664168983442',
    projectId: 'crypto-wallet-app-2fb95',
    storageBucket: 'crypto-wallet-app-2fb95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXU0R5eNa4Si80TNnC4Avjdv8A9A9kyMc',
    appId: '1:664168983442:ios:148a5d10e120beb8ccef4b',
    messagingSenderId: '664168983442',
    projectId: 'crypto-wallet-app-2fb95',
    storageBucket: 'crypto-wallet-app-2fb95.appspot.com',
    iosClientId: '664168983442-tm6r5to84c1d5bjt39opntp3j0b78brr.apps.googleusercontent.com',
    iosBundleId: 'com.example.metamaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXU0R5eNa4Si80TNnC4Avjdv8A9A9kyMc',
    appId: '1:664168983442:ios:148a5d10e120beb8ccef4b',
    messagingSenderId: '664168983442',
    projectId: 'crypto-wallet-app-2fb95',
    storageBucket: 'crypto-wallet-app-2fb95.appspot.com',
    iosClientId: '664168983442-tm6r5to84c1d5bjt39opntp3j0b78brr.apps.googleusercontent.com',
    iosBundleId: 'com.example.metamaskApp',
  );
}
